import React, { useEffect } from 'react';
import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from '@/app/common/header';
import "./globals.css";

export const metadata: Metadata = {
  title: "Uamaup ",
  description: "Generated by Toru",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/ummaup.png" type="image/png" sizes="16x16" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.1/font/bootstrap-icons.min.css" rel="stylesheet" />
      </head>
      <body>
        {/* <Header /> */}
        <div className="flex">
          {/* <LeftSidebar /> */}
          {children}
          {/* <RightSideBar /> */}
        </div>
        <footer>
        </footer>
      </body>
    </html>
  );
}
